FROM ubuntu:focal

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && apt-get install -y openssl wget

WORKDIR /root
COPY yezzey_test/generate_certs.sh /root

RUN ["./generate_certs.sh"]

RUN wget https://dl.min.io/server/minio/release/linux-amd64/minio \
&& chmod +x minio
