name: Run tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      # For testing
      - create_build_ci
  pull_request:
    branches:
      - YGP_6.27_STABLE


jobs:
  build_and_release:
    strategy:
        fail-fast: false
        matrix:
          # os: [ubuntu-latest, ubuntu-18.04]
          os : [ubuntu-20.04]
          compiler: [gcc]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo bash README.ubuntu.bash 
        
      
    - name: Build 
      run: | 
        ./configure --with-perl --with-python --with-libxml --with-gssapi --disable-orca --prefix=/usr/local/gpdb \
        --enable-depend --enable-cassert --enable-debug
        export GPHOME=/usr/local/gpdb/
        export PATH=$PATH:/usr/local/gpdb/bin
        make && make install
    
    - name: Check
      run: make check

    - name: Install check
      run: make installcheck

    - name: Test
      env:
        CC: ${{ matrix.compiler }}
        CC_FOR_BUILD: ${{ matrix.compiler }}
      run: make run_test
